version: 1.0.{build}

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master
  - /v[0-9]+\.[0-9]+\.[0-9]+/

image: Visual Studio 2017

environment:
  docspush_email: 32618965+cibuild-telliam@users.noreply.github.com
  docspush_username: cibuild-telliam
  docspush_access_token:
    secure: QqWCIyFM6uBBbkW1jnlVGsMQWy+9aPY9rhD56oNT2L/0Cmw2bynROEsrUrOPpBrk

skip_commits:
  files:
    - '**\*.md'

init:
  - git config --global core.safecrlf false
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true
  account_feed: false
  project_feed: false

build_script:
  - ps: .\BuildAll.ps1

deploy_script:
  - ps: .\Push-Docs.ps1

test_script:
  - dotnet test .\src\ArgValidator.Tests\ArgValidator.Tests.csproj -c Release --no-build -l Appveyor

artifacts:
  - path: BuildOutput/NuGet/**/*.nupkg
