version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

nuget:
  account_feed: false
  project_feed: false
  disable_publish_on_pr: true

before_build:
- cmd: msbuild /t:Restore src/Argument.Validators/Ubiquity.ArgValidators.csproj

build:
  project: src/Ubiquity.ArgValidators.sln
  verbosity: minimal

artifacts:
- path: BuildOutput/NuGet/**/*.nupkg