version: 1.0.{build}
image: Visual Studio 2017

nuget:
  project_feed: true
  disable_publish_on_pr: true

build:
  project: src/Ubiquity.ArgValidators.sln
  verbosity: minimal

artifacts:
- path: src\**.nupkg