//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubiquity.ArgValidators.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubiquity.ArgValidators.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted range: [{0}, {1}].
        /// </summary>
        internal static string Accepted_range_0_1_ {
            get {
                return ResourceManager.GetString("Accepted_range_0_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected string with length in the range [{0}, {1}].
        /// </summary>
        internal static string Expected_string_with_length_in_the_range_0_1_ {
            get {
                return ResourceManager.GetString("Expected_string_with_length_in_the_range_0_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be null or whitespace.
        /// </summary>
        internal static string Must_not_be_null_or_whitespace {
            get {
                return ResourceManager.GetString("Must_not_be_null_or_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must not be empty.
        /// </summary>
        internal static string String_Must_not_be_empty {
            get {
                return ResourceManager.GetString("String_Must_not_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must not contain only whitespace characters.
        /// </summary>
        internal static string String_must_not_be_whitespace {
            get {
                return ResourceManager.GetString("String_must_not_be_whitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ttt.
        /// </summary>
        internal static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not define an enumerated value for &apos;{1}&apos;.
        /// </summary>
        internal static string Type_0_does_not_define_an_enumerated_value_for_1_ {
            get {
                return ResourceManager.GetString("Type_0_does_not_define_an_enumerated_value_for_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value does not conform to required format: {0}.
        /// </summary>
        internal static string Value_does_not_conform_to_required_format_0_ {
            get {
                return ResourceManager.GetString("Value_does_not_conform_to_required_format_0_", resourceCulture);
            }
        }
    }
}
